// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsxCLa_ZXOZgx8yeTPw9CZofYHdAtKf9Y',
    appId: '1:751508784898:web:ff9667c407f1b7101c641b',
    messagingSenderId: '751508784898',
    projectId: 'railapp-b5fa5',
    authDomain: 'railapp-b5fa5.firebaseapp.com',
    storageBucket: 'railapp-b5fa5.appspot.com',
    measurementId: 'G-1NWFBX8PW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACiIrtTp5Nh-2LU1hCyxYXkqMS87UEIK0',
    appId: '1:751508784898:android:682a3ec6af6f350d1c641b',
    messagingSenderId: '751508784898',
    projectId: 'railapp-b5fa5',
    storageBucket: 'railapp-b5fa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaVPTR_MGM74YFk687R9r64WNs1nKUijg',
    appId: '1:751508784898:ios:2043c64f0967b0a31c641b',
    messagingSenderId: '751508784898',
    projectId: 'railapp-b5fa5',
    storageBucket: 'railapp-b5fa5.appspot.com',
    iosClientId: '751508784898-hdq5dm5lcd4berovl6jvsg12u6n9dpu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.railApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaVPTR_MGM74YFk687R9r64WNs1nKUijg',
    appId: '1:751508784898:ios:2043c64f0967b0a31c641b',
    messagingSenderId: '751508784898',
    projectId: 'railapp-b5fa5',
    storageBucket: 'railapp-b5fa5.appspot.com',
    iosClientId: '751508784898-hdq5dm5lcd4berovl6jvsg12u6n9dpu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.railApp',
  );
}
